// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalFinanceManagement.API.Database;

#nullable disable

namespace PesonalFinanceManagement.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20220727123857_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalFinanceManagement.API.Database.Entities.CategoryEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceManagement.API.Database.Entities.SplitTransactionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Catcode")
                        .HasColumnType("text");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("CategoryCode")
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id", "Catcode");

                    b.HasIndex("CategoryCode");

                    b.HasIndex("TransactionId");

                    b.ToTable("splitTransactions", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceManagement.API.Database.Entities.TransactionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("BeneficiaryName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Catcode")
                        .HasColumnType("text");

                    b.Property<string>("CategoryCode")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mcc")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("PersonalFinanceManagement.API.Database.Entities.SplitTransactionEntity", b =>
                {
                    b.HasOne("PersonalFinanceManagement.API.Database.Entities.CategoryEntity", "Category")
                        .WithMany("SplitTransactions")
                        .HasForeignKey("CategoryCode");

                    b.HasOne("PersonalFinanceManagement.API.Database.Entities.TransactionEntity", "Transaction")
                        .WithMany("SplitTransaction")
                        .HasForeignKey("TransactionId");

                    b.Navigation("Category");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PersonalFinanceManagement.API.Database.Entities.TransactionEntity", b =>
                {
                    b.HasOne("PersonalFinanceManagement.API.Database.Entities.CategoryEntity", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryCode");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PersonalFinanceManagement.API.Database.Entities.CategoryEntity", b =>
                {
                    b.Navigation("SplitTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PersonalFinanceManagement.API.Database.Entities.TransactionEntity", b =>
                {
                    b.Navigation("SplitTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
